/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_4bits(D_in, clk, en, D_out);
  wire [3:0] _0_;
  input [3:0] D_in;
  output [3:0] D_out;
  input clk;
  input en;
  sky130_fd_sc_hd__mux2_1 _1_ (
    .A0(D_out[2]),
    .A1(D_in[2]),
    .S(en),
    .X(_0_[2])
  );
  sky130_fd_sc_hd__mux2_1 _2_ (
    .A0(D_out[1]),
    .A1(D_in[1]),
    .S(en),
    .X(_0_[1])
  );
  sky130_fd_sc_hd__mux2_1 _3_ (
    .A0(D_out[0]),
    .A1(D_in[0]),
    .S(en),
    .X(_0_[0])
  );
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(D_out[3]),
    .A1(D_in[3]),
    .S(en),
    .X(_0_[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(clk),
    .D(_0_[0]),
    .Q(D_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _6_ (
    .CLK(clk),
    .D(_0_[1]),
    .Q(D_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _7_ (
    .CLK(clk),
    .D(_0_[2]),
    .Q(D_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _8_ (
    .CLK(clk),
    .D(_0_[3]),
    .Q(D_out[3])
  );
endmodule
