/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_1bit_16reg(d_in, clk, en, en2, en3, en4, en5, en6, en7, en8, en9, en10, en11, en12, en13, en14, en15, en16, d_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input clk;
  input d_in;
  output d_out;
  input en;
  input en10;
  input en11;
  input en12;
  input en13;
  input en14;
  input en15;
  input en16;
  input en2;
  input en3;
  input en4;
  input en5;
  input en6;
  input en7;
  input en8;
  input en9;
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(d_out),
    .A1(d_in),
    .S(en12),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(d_out),
    .A1(d_in),
    .S(en15),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(d_out),
    .A1(d_in),
    .S(en14),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(d_out),
    .A1(d_in),
    .S(en13),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(d_out),
    .A1(d_in),
    .S(en9),
    .X(_14_)
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(d_out),
    .A1(d_in),
    .S(en11),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _22_ (
    .A0(d_out),
    .A1(d_in),
    .S(en10),
    .X(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _23_ (
    .A0(d_out),
    .A1(d_in),
    .S(en6),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _24_ (
    .A0(d_out),
    .A1(d_in),
    .S(en8),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _25_ (
    .A0(d_out),
    .A1(d_in),
    .S(en7),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _26_ (
    .A0(d_out),
    .A1(d_in),
    .S(en3),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _27_ (
    .A0(d_out),
    .A1(d_in),
    .S(en5),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _28_ (
    .A0(d_out),
    .A1(d_in),
    .S(en4),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux2_1 _29_ (
    .A0(d_out),
    .A1(d_in),
    .S(en2),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _30_ (
    .A0(d_out),
    .A1(d_in),
    .S(en),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _31_ (
    .A0(d_out),
    .A1(d_in),
    .S(en16),
    .X(_06_)
  );
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(clk),
    .D(_06_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(clk),
    .D(_14_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(clk),
    .D(_05_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _35_ (
    .CLK(clk),
    .D(_04_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _36_ (
    .CLK(clk),
    .D(_03_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _37_ (
    .CLK(clk),
    .D(_02_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _38_ (
    .CLK(clk),
    .D(_01_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _39_ (
    .CLK(clk),
    .D(_15_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(clk),
    .D(_13_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _41_ (
    .CLK(clk),
    .D(_12_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(clk),
    .D(_11_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(clk),
    .D(_10_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(_09_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clk),
    .D(_08_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clk),
    .D(_07_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(_00_),
    .Q(d_out)
  );
endmodule
