/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_1bit_2reg(d_in, clk, en, en2, d_out);
  wire _0_;
  wire _1_;
  input clk;
  input d_in;
  output d_out;
  input en;
  input en2;
  sky130_fd_sc_hd__mux2_1 _2_ (
    .A0(d_out),
    .A1(d_in),
    .S(en),
    .X(_0_)
  );
  sky130_fd_sc_hd__mux2_1 _3_ (
    .A0(d_out),
    .A1(d_in),
    .S(en2),
    .X(_1_)
  );
  sky130_fd_sc_hd__dfxtp_1 _4_ (
    .CLK(clk),
    .D(_1_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(clk),
    .D(_0_),
    .Q(d_out)
  );
endmodule
