/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_4bits_8reg(d_in, clk, en, en2, en3, en4, en5, en6, en7, en8, d_out);
  wire [3:0] _00_;
  wire [3:0] _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  wire [3:0] _04_;
  wire [3:0] _05_;
  wire [3:0] _06_;
  wire [3:0] _07_;
  input clk;
  input [3:0] d_in;
  output [3:0] d_out;
  input en;
  input en2;
  input en3;
  input en4;
  input en5;
  input en6;
  input en7;
  input en8;
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en8),
    .X(_07_[2])
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en8),
    .X(_07_[1])
  );
  sky130_fd_sc_hd__mux2_1 _10_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en8),
    .X(_07_[0])
  );
  sky130_fd_sc_hd__mux2_1 _11_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en7),
    .X(_06_[1])
  );
  sky130_fd_sc_hd__mux2_1 _12_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en7),
    .X(_06_[3])
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en7),
    .X(_06_[2])
  );
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en6),
    .X(_05_[3])
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en7),
    .X(_06_[0])
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en6),
    .X(_05_[0])
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en6),
    .X(_05_[2])
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en6),
    .X(_05_[1])
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en5),
    .X(_04_[2])
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en5),
    .X(_04_[3])
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en5),
    .X(_04_[1])
  );
  sky130_fd_sc_hd__mux2_1 _22_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en5),
    .X(_04_[0])
  );
  sky130_fd_sc_hd__mux2_1 _23_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en4),
    .X(_03_[1])
  );
  sky130_fd_sc_hd__mux2_1 _24_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en4),
    .X(_03_[3])
  );
  sky130_fd_sc_hd__mux2_1 _25_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en4),
    .X(_03_[2])
  );
  sky130_fd_sc_hd__mux2_1 _26_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en3),
    .X(_02_[3])
  );
  sky130_fd_sc_hd__mux2_1 _27_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en4),
    .X(_03_[0])
  );
  sky130_fd_sc_hd__mux2_1 _28_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en3),
    .X(_02_[0])
  );
  sky130_fd_sc_hd__mux2_1 _29_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en3),
    .X(_02_[2])
  );
  sky130_fd_sc_hd__mux2_1 _30_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en3),
    .X(_02_[1])
  );
  sky130_fd_sc_hd__mux2_1 _31_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en2),
    .X(_01_[2])
  );
  sky130_fd_sc_hd__mux2_1 _32_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en2),
    .X(_01_[3])
  );
  sky130_fd_sc_hd__mux2_1 _33_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en2),
    .X(_01_[1])
  );
  sky130_fd_sc_hd__mux2_1 _34_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en2),
    .X(_01_[0])
  );
  sky130_fd_sc_hd__mux2_1 _35_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__mux2_1 _36_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__mux2_1 _37_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__mux2_1 _38_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__mux2_1 _39_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en8),
    .X(_07_[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(clk),
    .D(_07_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _41_ (
    .CLK(clk),
    .D(_07_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(clk),
    .D(_07_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(clk),
    .D(_07_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(_06_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clk),
    .D(_06_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clk),
    .D(_06_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(_06_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clk),
    .D(_05_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_05_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_05_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_05_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_04_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_04_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_04_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_04_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_03_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_03_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _58_ (
    .CLK(clk),
    .D(_03_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _59_ (
    .CLK(clk),
    .D(_03_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _60_ (
    .CLK(clk),
    .D(_02_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _61_ (
    .CLK(clk),
    .D(_02_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _62_ (
    .CLK(clk),
    .D(_02_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _63_ (
    .CLK(clk),
    .D(_02_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _64_ (
    .CLK(clk),
    .D(_01_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _65_ (
    .CLK(clk),
    .D(_01_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _66_ (
    .CLK(clk),
    .D(_01_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _67_ (
    .CLK(clk),
    .D(_01_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _68_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _69_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _70_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _71_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(d_out[3])
  );
endmodule
