/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_4bits_2reg(d_in, clk, en, en2, d_out);
  wire [3:0] _00_;
  wire [3:0] _01_;
  input clk;
  input [3:0] d_in;
  output [3:0] d_out;
  input en;
  input en2;
  sky130_fd_sc_hd__mux2_1 _02_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en2),
    .X(_01_[2])
  );
  sky130_fd_sc_hd__mux2_1 _03_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en2),
    .X(_01_[1])
  );
  sky130_fd_sc_hd__mux2_1 _04_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en2),
    .X(_01_[0])
  );
  sky130_fd_sc_hd__mux2_1 _05_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__mux2_1 _06_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__mux2_1 _07_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en2),
    .X(_01_[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _10_ (
    .CLK(clk),
    .D(_01_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _11_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _12_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _13_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _14_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _15_ (
    .CLK(clk),
    .D(_01_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_01_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_01_[2]),
    .Q(d_out[2])
  );
endmodule
