/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_1bit_8reg(d_in, clk, en, en2, en3, en4, en5, en6, en7, en8, d_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input clk;
  input d_in;
  output d_out;
  input en;
  input en2;
  input en3;
  input en4;
  input en5;
  input en6;
  input en7;
  input en8;
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(d_out),
    .A1(d_in),
    .S(en7),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(d_out),
    .A1(d_in),
    .S(en6),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _10_ (
    .A0(d_out),
    .A1(d_in),
    .S(en2),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _11_ (
    .A0(d_out),
    .A1(d_in),
    .S(en3),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _12_ (
    .A0(d_out),
    .A1(d_in),
    .S(en),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(d_out),
    .A1(d_in),
    .S(en4),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(d_out),
    .A1(d_in),
    .S(en5),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(d_out),
    .A1(d_in),
    .S(en8),
    .X(_07_)
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_01_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_07_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_06_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_05_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_04_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_03_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(_02_),
    .Q(d_out)
  );
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(clk),
    .D(_00_),
    .Q(d_out)
  );
endmodule
