/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_4bits_16reg(d_in, clk, en, en2, en3, en4, en5, en6, en7, en8, en9, en10, en11, en12, en13, en14, en15, en16, d_out);
  wire [3:0] _000_;
  wire [3:0] _001_;
  wire [3:0] _002_;
  wire [3:0] _003_;
  wire [3:0] _004_;
  wire [3:0] _005_;
  wire [3:0] _006_;
  wire [3:0] _007_;
  wire [3:0] _008_;
  wire [3:0] _009_;
  wire [3:0] _010_;
  wire [3:0] _011_;
  wire [3:0] _012_;
  wire [3:0] _013_;
  wire [3:0] _014_;
  wire [3:0] _015_;
  input clk;
  input [3:0] d_in;
  output [3:0] d_out;
  input en;
  input en10;
  input en11;
  input en12;
  input en13;
  input en14;
  input en15;
  input en16;
  input en2;
  input en3;
  input en4;
  input en5;
  input en6;
  input en7;
  input en8;
  input en9;
  sky130_fd_sc_hd__mux2_1 _016_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en16),
    .X(_006_[2])
  );
  sky130_fd_sc_hd__mux2_1 _017_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en16),
    .X(_006_[1])
  );
  sky130_fd_sc_hd__mux2_1 _018_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en16),
    .X(_006_[0])
  );
  sky130_fd_sc_hd__mux2_1 _019_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en15),
    .X(_005_[1])
  );
  sky130_fd_sc_hd__mux2_1 _020_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en15),
    .X(_005_[3])
  );
  sky130_fd_sc_hd__mux2_1 _021_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en15),
    .X(_005_[2])
  );
  sky130_fd_sc_hd__mux2_1 _022_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en14),
    .X(_004_[3])
  );
  sky130_fd_sc_hd__mux2_1 _023_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en15),
    .X(_005_[0])
  );
  sky130_fd_sc_hd__mux2_1 _024_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en14),
    .X(_004_[0])
  );
  sky130_fd_sc_hd__mux2_1 _025_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en14),
    .X(_004_[2])
  );
  sky130_fd_sc_hd__mux2_1 _026_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en14),
    .X(_004_[1])
  );
  sky130_fd_sc_hd__mux2_1 _027_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en13),
    .X(_003_[2])
  );
  sky130_fd_sc_hd__mux2_1 _028_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en13),
    .X(_003_[3])
  );
  sky130_fd_sc_hd__mux2_1 _029_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en13),
    .X(_003_[1])
  );
  sky130_fd_sc_hd__mux2_1 _030_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en13),
    .X(_003_[0])
  );
  sky130_fd_sc_hd__mux2_1 _031_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en12),
    .X(_002_[1])
  );
  sky130_fd_sc_hd__mux2_1 _032_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en12),
    .X(_002_[3])
  );
  sky130_fd_sc_hd__mux2_1 _033_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en12),
    .X(_002_[2])
  );
  sky130_fd_sc_hd__mux2_1 _034_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en11),
    .X(_001_[3])
  );
  sky130_fd_sc_hd__mux2_1 _035_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en12),
    .X(_002_[0])
  );
  sky130_fd_sc_hd__mux2_1 _036_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en11),
    .X(_001_[0])
  );
  sky130_fd_sc_hd__mux2_1 _037_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en11),
    .X(_001_[2])
  );
  sky130_fd_sc_hd__mux2_1 _038_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en11),
    .X(_001_[1])
  );
  sky130_fd_sc_hd__mux2_1 _039_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en10),
    .X(_015_[2])
  );
  sky130_fd_sc_hd__mux2_1 _040_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en10),
    .X(_015_[3])
  );
  sky130_fd_sc_hd__mux2_1 _041_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en10),
    .X(_015_[1])
  );
  sky130_fd_sc_hd__mux2_1 _042_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en10),
    .X(_015_[0])
  );
  sky130_fd_sc_hd__mux2_1 _043_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en9),
    .X(_014_[1])
  );
  sky130_fd_sc_hd__mux2_1 _044_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en9),
    .X(_014_[3])
  );
  sky130_fd_sc_hd__mux2_1 _045_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en9),
    .X(_014_[2])
  );
  sky130_fd_sc_hd__mux2_1 _046_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en8),
    .X(_013_[3])
  );
  sky130_fd_sc_hd__mux2_1 _047_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en9),
    .X(_014_[0])
  );
  sky130_fd_sc_hd__mux2_1 _048_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en8),
    .X(_013_[0])
  );
  sky130_fd_sc_hd__mux2_1 _049_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en8),
    .X(_013_[2])
  );
  sky130_fd_sc_hd__mux2_1 _050_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en8),
    .X(_013_[1])
  );
  sky130_fd_sc_hd__mux2_1 _051_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en7),
    .X(_012_[2])
  );
  sky130_fd_sc_hd__mux2_1 _052_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en7),
    .X(_012_[3])
  );
  sky130_fd_sc_hd__mux2_1 _053_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en7),
    .X(_012_[1])
  );
  sky130_fd_sc_hd__mux2_1 _054_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en7),
    .X(_012_[0])
  );
  sky130_fd_sc_hd__mux2_1 _055_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en6),
    .X(_011_[1])
  );
  sky130_fd_sc_hd__mux2_1 _056_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en6),
    .X(_011_[3])
  );
  sky130_fd_sc_hd__mux2_1 _057_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en6),
    .X(_011_[2])
  );
  sky130_fd_sc_hd__mux2_1 _058_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en5),
    .X(_010_[3])
  );
  sky130_fd_sc_hd__mux2_1 _059_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en6),
    .X(_011_[0])
  );
  sky130_fd_sc_hd__mux2_1 _060_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en5),
    .X(_010_[0])
  );
  sky130_fd_sc_hd__mux2_1 _061_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en5),
    .X(_010_[2])
  );
  sky130_fd_sc_hd__mux2_1 _062_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en5),
    .X(_010_[1])
  );
  sky130_fd_sc_hd__mux2_1 _063_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en4),
    .X(_009_[2])
  );
  sky130_fd_sc_hd__mux2_1 _064_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en4),
    .X(_009_[3])
  );
  sky130_fd_sc_hd__mux2_1 _065_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en4),
    .X(_009_[1])
  );
  sky130_fd_sc_hd__mux2_1 _066_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en4),
    .X(_009_[0])
  );
  sky130_fd_sc_hd__mux2_1 _067_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en3),
    .X(_008_[1])
  );
  sky130_fd_sc_hd__mux2_1 _068_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en3),
    .X(_008_[3])
  );
  sky130_fd_sc_hd__mux2_1 _069_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en3),
    .X(_008_[2])
  );
  sky130_fd_sc_hd__mux2_1 _070_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en2),
    .X(_007_[3])
  );
  sky130_fd_sc_hd__mux2_1 _071_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en3),
    .X(_008_[0])
  );
  sky130_fd_sc_hd__mux2_1 _072_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en2),
    .X(_007_[0])
  );
  sky130_fd_sc_hd__mux2_1 _073_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en2),
    .X(_007_[2])
  );
  sky130_fd_sc_hd__mux2_1 _074_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en2),
    .X(_007_[1])
  );
  sky130_fd_sc_hd__mux2_1 _075_ (
    .A0(d_out[2]),
    .A1(d_in[2]),
    .S(en),
    .X(_000_[2])
  );
  sky130_fd_sc_hd__mux2_1 _076_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__mux2_1 _077_ (
    .A0(d_out[1]),
    .A1(d_in[1]),
    .S(en),
    .X(_000_[1])
  );
  sky130_fd_sc_hd__mux2_1 _078_ (
    .A0(d_out[0]),
    .A1(d_in[0]),
    .S(en),
    .X(_000_[0])
  );
  sky130_fd_sc_hd__mux2_1 _079_ (
    .A0(d_out[3]),
    .A1(d_in[3]),
    .S(en16),
    .X(_006_[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _080_ (
    .CLK(clk),
    .D(_006_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _081_ (
    .CLK(clk),
    .D(_006_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _082_ (
    .CLK(clk),
    .D(_006_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _083_ (
    .CLK(clk),
    .D(_006_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _084_ (
    .CLK(clk),
    .D(_005_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _085_ (
    .CLK(clk),
    .D(_005_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _086_ (
    .CLK(clk),
    .D(_005_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _087_ (
    .CLK(clk),
    .D(_005_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _088_ (
    .CLK(clk),
    .D(_004_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _089_ (
    .CLK(clk),
    .D(_004_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _090_ (
    .CLK(clk),
    .D(_004_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _091_ (
    .CLK(clk),
    .D(_004_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _092_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _093_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _094_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _095_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _096_ (
    .CLK(clk),
    .D(_002_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _097_ (
    .CLK(clk),
    .D(_002_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _098_ (
    .CLK(clk),
    .D(_002_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _099_ (
    .CLK(clk),
    .D(_002_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _100_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _101_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _102_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _103_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _104_ (
    .CLK(clk),
    .D(_015_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _105_ (
    .CLK(clk),
    .D(_015_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _106_ (
    .CLK(clk),
    .D(_015_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _107_ (
    .CLK(clk),
    .D(_015_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _108_ (
    .CLK(clk),
    .D(_014_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _109_ (
    .CLK(clk),
    .D(_014_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _110_ (
    .CLK(clk),
    .D(_014_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _111_ (
    .CLK(clk),
    .D(_014_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _112_ (
    .CLK(clk),
    .D(_013_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _113_ (
    .CLK(clk),
    .D(_013_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _114_ (
    .CLK(clk),
    .D(_013_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _115_ (
    .CLK(clk),
    .D(_013_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _116_ (
    .CLK(clk),
    .D(_012_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _117_ (
    .CLK(clk),
    .D(_012_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _118_ (
    .CLK(clk),
    .D(_012_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _119_ (
    .CLK(clk),
    .D(_012_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _120_ (
    .CLK(clk),
    .D(_011_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _121_ (
    .CLK(clk),
    .D(_011_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _122_ (
    .CLK(clk),
    .D(_011_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _123_ (
    .CLK(clk),
    .D(_011_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _124_ (
    .CLK(clk),
    .D(_010_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _125_ (
    .CLK(clk),
    .D(_010_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _126_ (
    .CLK(clk),
    .D(_010_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _127_ (
    .CLK(clk),
    .D(_010_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _128_ (
    .CLK(clk),
    .D(_009_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _129_ (
    .CLK(clk),
    .D(_009_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _130_ (
    .CLK(clk),
    .D(_009_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _131_ (
    .CLK(clk),
    .D(_009_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _132_ (
    .CLK(clk),
    .D(_008_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _133_ (
    .CLK(clk),
    .D(_008_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _134_ (
    .CLK(clk),
    .D(_008_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _135_ (
    .CLK(clk),
    .D(_008_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _136_ (
    .CLK(clk),
    .D(_007_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _137_ (
    .CLK(clk),
    .D(_007_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _138_ (
    .CLK(clk),
    .D(_007_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _139_ (
    .CLK(clk),
    .D(_007_[3]),
    .Q(d_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _140_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(d_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _141_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(d_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _142_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(d_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _143_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(d_out[3])
  );
endmodule
