/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test_32bits(D_in, clk, en, D_out);
  wire [31:0] _00_;
  input [31:0] D_in;
  output [31:0] D_out;
  input clk;
  input en;
  sky130_fd_sc_hd__mux2_1 _01_ (
    .A0(D_out[30]),
    .A1(D_in[30]),
    .S(en),
    .X(_00_[30])
  );
  sky130_fd_sc_hd__mux2_1 _02_ (
    .A0(D_out[27]),
    .A1(D_in[27]),
    .S(en),
    .X(_00_[27])
  );
  sky130_fd_sc_hd__mux2_1 _03_ (
    .A0(D_out[29]),
    .A1(D_in[29]),
    .S(en),
    .X(_00_[29])
  );
  sky130_fd_sc_hd__mux2_1 _04_ (
    .A0(D_out[28]),
    .A1(D_in[28]),
    .S(en),
    .X(_00_[28])
  );
  sky130_fd_sc_hd__mux2_1 _05_ (
    .A0(D_out[24]),
    .A1(D_in[24]),
    .S(en),
    .X(_00_[24])
  );
  sky130_fd_sc_hd__mux2_1 _06_ (
    .A0(D_out[26]),
    .A1(D_in[26]),
    .S(en),
    .X(_00_[26])
  );
  sky130_fd_sc_hd__mux2_1 _07_ (
    .A0(D_out[25]),
    .A1(D_in[25]),
    .S(en),
    .X(_00_[25])
  );
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(D_out[21]),
    .A1(D_in[21]),
    .S(en),
    .X(_00_[21])
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(D_out[23]),
    .A1(D_in[23]),
    .S(en),
    .X(_00_[23])
  );
  sky130_fd_sc_hd__mux2_1 _10_ (
    .A0(D_out[22]),
    .A1(D_in[22]),
    .S(en),
    .X(_00_[22])
  );
  sky130_fd_sc_hd__mux2_1 _11_ (
    .A0(D_out[18]),
    .A1(D_in[18]),
    .S(en),
    .X(_00_[18])
  );
  sky130_fd_sc_hd__mux2_1 _12_ (
    .A0(D_out[20]),
    .A1(D_in[20]),
    .S(en),
    .X(_00_[20])
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(D_out[19]),
    .A1(D_in[19]),
    .S(en),
    .X(_00_[19])
  );
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(D_out[15]),
    .A1(D_in[15]),
    .S(en),
    .X(_00_[15])
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(D_out[17]),
    .A1(D_in[17]),
    .S(en),
    .X(_00_[17])
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(D_out[16]),
    .A1(D_in[16]),
    .S(en),
    .X(_00_[16])
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(D_out[12]),
    .A1(D_in[12]),
    .S(en),
    .X(_00_[12])
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(D_out[14]),
    .A1(D_in[14]),
    .S(en),
    .X(_00_[14])
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(D_out[13]),
    .A1(D_in[13]),
    .S(en),
    .X(_00_[13])
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(D_out[9]),
    .A1(D_in[9]),
    .S(en),
    .X(_00_[9])
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(D_out[11]),
    .A1(D_in[11]),
    .S(en),
    .X(_00_[11])
  );
  sky130_fd_sc_hd__mux2_1 _22_ (
    .A0(D_out[10]),
    .A1(D_in[10]),
    .S(en),
    .X(_00_[10])
  );
  sky130_fd_sc_hd__mux2_1 _23_ (
    .A0(D_out[6]),
    .A1(D_in[6]),
    .S(en),
    .X(_00_[6])
  );
  sky130_fd_sc_hd__mux2_1 _24_ (
    .A0(D_out[8]),
    .A1(D_in[8]),
    .S(en),
    .X(_00_[8])
  );
  sky130_fd_sc_hd__mux2_1 _25_ (
    .A0(D_out[7]),
    .A1(D_in[7]),
    .S(en),
    .X(_00_[7])
  );
  sky130_fd_sc_hd__mux2_1 _26_ (
    .A0(D_out[3]),
    .A1(D_in[3]),
    .S(en),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__mux2_1 _27_ (
    .A0(D_out[5]),
    .A1(D_in[5]),
    .S(en),
    .X(_00_[5])
  );
  sky130_fd_sc_hd__mux2_1 _28_ (
    .A0(D_out[4]),
    .A1(D_in[4]),
    .S(en),
    .X(_00_[4])
  );
  sky130_fd_sc_hd__mux2_1 _29_ (
    .A0(D_out[0]),
    .A1(D_in[0]),
    .S(en),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__mux2_1 _30_ (
    .A0(D_out[2]),
    .A1(D_in[2]),
    .S(en),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__mux2_1 _31_ (
    .A0(D_out[1]),
    .A1(D_in[1]),
    .S(en),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__mux2_1 _32_ (
    .A0(D_out[31]),
    .A1(D_in[31]),
    .S(en),
    .X(_00_[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(D_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(D_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _35_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(D_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _36_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(D_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _37_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(D_out[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _38_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(D_out[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _39_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(D_out[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(D_out[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _41_ (
    .CLK(clk),
    .D(_00_[8]),
    .Q(D_out[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(clk),
    .D(_00_[9]),
    .Q(D_out[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(clk),
    .D(_00_[10]),
    .Q(D_out[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(_00_[11]),
    .Q(D_out[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clk),
    .D(_00_[12]),
    .Q(D_out[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clk),
    .D(_00_[13]),
    .Q(D_out[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(_00_[14]),
    .Q(D_out[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clk),
    .D(_00_[15]),
    .Q(D_out[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_00_[16]),
    .Q(D_out[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_00_[17]),
    .Q(D_out[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_00_[18]),
    .Q(D_out[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_00_[19]),
    .Q(D_out[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_00_[20]),
    .Q(D_out[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_00_[21]),
    .Q(D_out[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_00_[22]),
    .Q(D_out[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_00_[23]),
    .Q(D_out[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_00_[24]),
    .Q(D_out[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _58_ (
    .CLK(clk),
    .D(_00_[25]),
    .Q(D_out[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _59_ (
    .CLK(clk),
    .D(_00_[26]),
    .Q(D_out[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _60_ (
    .CLK(clk),
    .D(_00_[27]),
    .Q(D_out[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _61_ (
    .CLK(clk),
    .D(_00_[28]),
    .Q(D_out[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _62_ (
    .CLK(clk),
    .D(_00_[29]),
    .Q(D_out[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _63_ (
    .CLK(clk),
    .D(_00_[30]),
    .Q(D_out[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _64_ (
    .CLK(clk),
    .D(_00_[31]),
    .Q(D_out[31])
  );
endmodule
